### PR TITLE
2.0rc27

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
See #3 for context.

ping @mdraw @omry

**Comment by hadim** [comment]
LGTM

**Comment by mdraw** [comment]
Thanks, merged

**Comment by hadim** [comment]
The rc package can be installed with:

```
conda install -c conda-forge/label/rc omegaconf
```

**Comment by omry** [comment]
Awesome!

In the mean time, I adjusted the [README](https://github.com/omry/omegaconf/blob/c2d6bb1b41f0273b09f7174f1027cfa7634d1def/README.md) to encourage people to use the 2.0 RC instead of 1.4 stable.

I also released rc28 and updated the [release notes](https://github.com/omry/omegaconf/releases/tag/2.0.0rc28) to include all the changes there.

With the exceptions of new bugs, I am done with 2.0 changes and will make it an official release once the major downstream project is ready with it's new version (Hydra, is getting close too).

**Comment by mdraw** [comment]
@hadim I'll submit a PR for the 2.0.0 update soon. Should I add you as an additional feedstock maintainer while doing this?

**Comment by hadim** [comment]
Great. Thank you I don't really need to be a maintener. You can ping me of you need help.

**Comment by omry** [comment]
@hadim, it would be great if you can continue to support it.
I certainly don't have the cycles and I think it's unfair for @mdraw to be the only one doing this as he has no interest in OmegaConf as far as I know.

**Comment by mdraw** [comment]
@omry I do have interest in OmegaConf and I'm happily using it in a closed codebase. By the way, it works very well - it was easy to integrate and especially the custom interpolator feature came in handy a few times. I think I said somewhere in the OmegaConf chat that I don't use hydra, just OmegaConf, so maybe that's the source of the confusion. I will evaluate hydra after the 1.0 release and see where it fits in my projects.

**Comment by omry** [comment]
Oh, sorry @mdraw! you created the Hydra conda package! for some reason I got confused and thought you are working on conda forge in general.

**Comment by hadim** [comment]
If you want you can add me, it's fine. Maintaining this repo is mainly pushing the green button for each new releases since everything is automatic. And you can also ping conda forge devs whenever you have questions.

**Pull request merged**
