### PR TITLE
update to v2.2.2

### PR DESCRIPTION
**Pull request by Jhsmit**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

I'm trying to get v.2.2.2 on conda forge
As far as I can tell both patches are no longer needed as omegaconf now uses antlr-4.9 and the pypy test patch was implemented in the tests.

### CODE REVIEW

**Comment by Jhsmit** [comment]
@conda-forge-admin please rerender

**Comment by Jhsmit** [comment]
@mdraw do you have any suggestions as to how to deal with the one py39 windows test failing?

**Comment by mdraw** [comment]
No, I don't understand it either. Windows py39 CPython runs fine, Windows py38 PyPy works as well, only Windows py39 PyPy doesn't work, but I don't see any meaningful error message.

**Comment by Jhsmit** [comment]
Ok it looks like it was a fluke
@mdraw , could you review and merge?

**Pull request merged**
