### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by benjaminrwilson**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by omry** [comment]
The mac failure is really strange: tests are passing when I run this on mac (even though the CI in OmegaConf is not testing on Mac).
Any idea about what could be causing the different behavior?

**Comment by benjaminrwilson** [comment]
Yeah, I'm not sure. It also is happening on `linux` here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=343197&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0&l=2282. It looks like it doesn't like: https://github.com/omry/omegaconf/blob/155d5c4de299b1c56762c04e2ea1b1fe8a5d9ad2/tests/test_errors.py#L1514.

**Comment by omry** [comment]
This is very strange. OmegaConf tests are running fine on Linux.
The error seems to be when comparing the expected message. Any reason for a system newline difference?

Are you able to reproduce it outside of Azure?

**Comment by benjaminrwilson** [comment]
No, I'm not. @isuruf and @chrisburr, what are your thoughts?

**Comment by isuruf** [comment]
mac and linux x86_64 failures are for PyPy and that's because the exception message is slightly different I guess.

**Comment by omry** [comment]
I wouldn't expect a difference in the exception message.
In general we are not testing on pypy right now, so it is possible.

@jasha10, can you try to reproduce the problem with [pypy](https://www.pypy.org/)?

**Comment by Jasha10** [comment]
Yes, I'll get started on it.

**Comment by Jasha10** [comment]
I was able to reproduce the pypy issue on my local machine.
On CPython we get `ZeroDivisionError: float division by zero`, and on Pypy we get `ZeroDivisionError: float division`.

**Comment by isuruf** [comment]
CCing @mattip just in case this is unintentional on PyPy's side.

**Comment by benjaminrwilson** [comment]
@isuruf, @omry, and @Jasha10 -- I've added a patch for https://github.com/omry/omegaconf/pull/764, but the osx-arm64 build is still failing on running `java`. It appears to be working locally for me (on osx-arm64). Any idea what might cause this?

**Comment by isuruf** [comment]
You should move `antlr` to build because we are cross compiling for osx-arm64.

**Comment by benjaminrwilson** [comment]
@omry Ready for merge.

**Comment by mattip** [comment]
> I wouldn't expect a difference in the exception message.

Well, PyPy tries to be 100% CPython compatible but sometimes misses. Fixed in PyPy for the next release, thanks.

**Comment by omry** [comment]
Awesome. thanks for fixing pypy @mattip.

This looks good to me.

**Comment by omry** [comment]
I wish there was a cleaner way to avoid the pydev tests. this seems fragile.

**Comment by benjaminrwilson** [comment]
Yeah, I agree. I guess we could look into adding `pydev` to `conda-forge` as a long term solution?

**Comment by omry** [comment]
> Yeah, I agree. I guess we could look into adding `pydev` to `conda-forge` as a long term solution?

This seems to be skipping the pydev tests when I run it:
```
$ pytest --ignore tests/test_pydev_resolver_plugin.py
```

**Comment by benjaminrwilson** [comment]
@omry, should be fixed now!

**Review by omry — APPROVED** [review]
lgtm, thanks!

**Comment by omry** [comment]
@mdraw, do you mind taking a look and merging if it looks okay from the Conda POV?

**Review by mdraw — APPROVED** [review]
I'm not an expert here but to my eyes everything looks good now👍

**Pull request merged**
